services:
  openvpn-simple:
    image: tmpjg/docker-openvpn-simple:latest
    container_name: openvpn-simple
    network_mode: host
    environment:
      - OPENVPN_CN=${OPENVPN_CN}
      - OPENVPN_REMOTE=${OPENVPN_REMOTE}
      - OPENVPN_REMOTE_PORT=${OPENVPN_REMOTE_PORT}
#    ports: # not needed with network_mode hosts
#      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data:/etc/openvpn
      - ./logs:/var/log/openvpn
      - /dev/net/tun:/dev/net/tun
    restart: always
    command: "openvpn_run" 
